apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
  namespace: infra
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - name: awscli
        image: amazon/aws-cli:2.0.22
        imagePullPolicy: Always # IfNotPresent
        command:
        - aws
        - --version
