---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: skcc05599
  region: ap-northeast-2
  version: "1.16"
vpc:
  cidr: 100.64.0.0/21       # Main CIDR : 100.64.0.0 ~ 100.64.7.255
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]
nodeGroups: []
managedNodeGroups: []
