---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: skcc05599
  region: ap-northeast-2
  version: "1.16"
vpc:
  cidr: 10.5.0.0/16       # Main CIDR : 10.5.0.0 ~ 10.5.255.255
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
managedNodeGroups:
  - name: devops-managed-new
    tags:
      nodegroup-name: devops
      creator: skcc05599
    labels:
      role: devops
      nodegroup-type: managed
      ec2-type: t3a.large   # t3a.medium = 2/4, t3a.large = 2/8 => t3.medium under MemoryPressure during gitlab & jenkins
    instanceType: t3a.large # t3a.medium = 2/4, t3a.large = 2/8
    # ami: ami-0b18567e6d3b05548 # only for nodeGroups( Unmanaged nodegroup )
    availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]    
    minSize: 1 
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 40
    privateNetworking: true
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        ebs: true    # CSI Driver
        autoScaler: true
        cloudWatch: true
        imageBuilder: true
