---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: skcc05599
  region: ap-northeast-2
  version: "1.15"
vpc:
  cidr: 10.5.0.0/16       # Main CIDR : 10.5.0.0 ~ 10.5.255.255
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
managedNodeGroups:
  - name: workers
    tags:
      nodegroup-name: worker
      creator: skcc05599
    labels:
      role: worker
      nodegroup-type: managed
      ec2-type: t3a.micro # t3.micro = Noly 1 POD
    instanceType: t3a.micro # t3.micro = Noly 1 POD
    availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]    
    minSize: 2
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        efs: true    # CSI Driver
        ebs: true    # CSI Driver
        autoScaler: true
        cloudWatch: true
        imageBuilder: true
