apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-app
  namespace: test
  labels:
    app: apple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple 
  template:
    metadata:
      labels:
        app: apple 
    spec:
      containers:
      - name: apple-app
        image: hashicorp/http-echo
        imagePullPolicy: Always # IfNotPresent
        args:
        - "-text=<html><header><title>Apple</title></header><body>ffptest.com/apple</body></html>"
      nodeSelector:
        role: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana-app
  namespace: test
  labels:
    app: banana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
      - name: banana-app
        image: hashicorp/http-echo
        imagePullPolicy: Always # IfNotPresent
        args:
        - "-text=<html><header><title>Banana</title></header><body>ffptest.com/banana</body></html>"
      nodeSelector:
        role: worker
---
kind: Service
apiVersion: v1
metadata:
  name: apple-service
  namespace: test
spec:
  selector:
    app: apple
  ports:
  - port: 5678 # Default port for image
---
kind: Service
apiVersion: v1
metadata:
  name: banana-service
  namespace: test
spec:
  selector:
    app: banana
  ports:
  - port: 5678 # Default port for image
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apple-banana
  namespace: test
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ffptest.com
    http:
      paths:
        - path: /apple
          backend:
            serviceName: apple-service 
            servicePort: 5678
        - path: /banana
          backend:
            serviceName: banana-service 
            servicePort: 5678
  # This section is only required if TLS is to be enabled for the Ingress
  #tls:
  #    - hosts:
  #        - www.example.com
  #      secretName: example-tls
