apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-pvc
  namespace: infra
  labels:
    app: busybox-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: nginx
        image: 847322629192.dkr.ecr.ap-northeast-2.amazonaws.com/busybox:latest
        imagePullPolicy: Always # IfNotPresent
        command:
          - sleep
          - "3600"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/gitlab
          - name: log
            mountPath: /var/log/gitlab
          - name: data
            mountPath: /var/opt/gitlab
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: gitlab-ce-config
      - name: log
        persistentVolumeClaim:
          claimName: gitlab-ce-log
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-ce-data
